### ISSUE TITLE
TLS charm in bundle needs to be updated

### ISSUE THREAD

**Issue by a-velasco** [canonical/postgresql-k8s-bundle#78]
https://github.com/canonical/postgresql-k8s-bundle/blob/f38af95e474c0f7552756157e1422b3bba472fd2/releases/latest/postgresql-k8s-bundle.yaml#L15-L22

This bundle is still using the old `tls-certificates-operator` and should be updated to [`self-signed-certificates`](https://charmhub.io/self-signed-certificates).

**Comment by dragomirp** [comment]
Bundle is updated with the current cert charm.
